image:
    registry.gitlab.com/etherlab.org/build-container-factory/leap-15.2:linux-syms

build:
    stage: build

    script:
        - ./bootstrap
        - ./configure --with-linux-dir=/usr/src/linux-obj/$(uname -i)/default --disable-8139too
        - make -j8 all modules
        - make DISTCHECK_CONFIGURE_FLAGS="--with-linux-dir=/usr/src/linux-obj/$(uname -i)/default" distcheck

include:
    - template: 'Workflows/MergeRequest-Pipelines.gitlab-ci.yml'
